name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build-lint-test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-arm]
        include:
          - os: windows-latest
            checkTarget: true
          - os: ubuntu-latest
          - os: ubuntu-arm
            runsOn: ubuntu-24.04-arm64-2-core
    runs-on: ${{ matrix.runsOn || matrix.os }}
    steps:
      - name: Print build information
        run: "echo head_ref: ${{ github.head_ref }}, ref: ${{ github.ref }}, os: ${{ matrix.os }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Build
        run: dotnet build

      - name: Check format
        if: ${{ matrix.checkTarget }}
        run: dotnet format --verify-no-changes

      - name: Test
        run: dotnet test --logger "console;verbosity=detailed" --blame-crash -v n

      - name: Upload test failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-fail-${{ matrix.os }}
          path: tests/TestResults
